name: Fetch
on:
  schedule:
    # Run at 3:00 AM UTC (11:00 AM Singapore time) every day
    - cron: '0 3 * * *'
  workflow_dispatch:  # Allow manual triggering as well
jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '>=3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install boto3
          pip install awscli  # Install AWS CLI
      - name: Fetch headlines and update latest database
        env:
          JINA_API_TOKEN: ${{ secrets.JINA_API_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          AWS_REQUEST_CHECKSUM_CALCULATION: when_required
          AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
        run: |
          # First, update the "latest" version directly
          echo "Fetching headlines and updating latest database"
          sglawwatch-to-sqlite fetch all "s3://$S3_BUCKET_NAME/latest/"
          
          # Then create a backup copy in a date-based folder
          DATE_PATH=$(date +"%Y/%m/%d")
          BACKUP_PATH="archives/$DATE_PATH"
          echo "Creating backup copy at $BACKUP_PATH"
          
          # Debug output
          echo "Source: s3://$S3_BUCKET_NAME/latest/sglawwatch.db"
          echo "Destination: s3://$S3_BUCKET_NAME/$BACKUP_PATH/sglawwatch.db"
          echo "Endpoint URL: $S3_ENDPOINT_URL"
          
          # Copy from latest to dated backup location
          aws s3 cp "s3://$S3_BUCKET_NAME/latest/sglawwatch.db" \
            "s3://$S3_BUCKET_NAME/$BACKUP_PATH/sglawwatch.db" \
            --endpoint-url "$S3_ENDPOINT_URL" \
            --region default
          
          echo "Successfully fetched headlines and created backup"
